[workspace]
resolver = "2"
members = [
    "classic"
    , "composition"
    , "dream-catcher"
    , "game_with_bevy"
    , "game_without_bevy"
    , "hello_ecs"
    , "inside_bevy", "pong", "robotic"
    , "simple_ecs"
    , "simple_ecs_2"
]
